TieBa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('tiebas.urls', 'tiebas'))),
    path('users/', include(('users.urls', 'users'))),
]

tiebas/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    #主页
    path('', views.index, name='index'),
    #显示所有的帖子主题
    path('topics/', views.topics, name='topics'),
    #显示特定帖子
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    #评论
    path('update_comment/', views.update_comment, name='update_comment'),
    #删除楼层
    re_path(r'^poster_del/(?P<id>\d+)/$', views.poster_del, name='poster_del'),
    #删除回复
    re_path(r'^reply_del/(?P<id>\d+)/$', views.reply_del, name='reply_del'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
]

tiebas/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    """贴吧帖子主题"""
    text_topic = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    floor_many = models.IntegerField()

    def __str__(self):
        return self.text_topic

class poster(models.Model):
    """贴吧帖子"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text_poster = models.TextField()
    floor = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'posters'

    def __str__(self):
        return self.text_poster[:50] + '...'

class Poster_reply(models.Model):
    """帖子回复"""
    poster = models.ForeignKey(poster, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)

    by_owner = models.ForeignKey(User, null=True, related_name="replies", on_delete=models.SET_NULL)

    def __str__(self):
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

tiebas/forms.py
from django import forms
from .models import Topic, poster, Poster_reply
from django.core.exceptions import ValidationError

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text_topic']
        labels = {'text_topic': ''}

class PosterForm(forms.ModelForm):
    class Meta:
        model = poster
        fields = ['text_poster']
        labels = {'text_poster': ''}
        widgets = {'text_poster': forms.Textarea(attrs={'cols': 80})}

class PosterReplyForm(forms.Form):
    text = forms.CharField()

tiebas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import Topic, poster, Poster_reply
from .forms import TopicForm, PosterForm, PosterReplyForm
from django.db.models import Max
# Create your views here.
def index(request):
    """贴吧主页"""
    return render(request, 'tiebas/index.html')

def topics(request):
    """显示所有帖子主题"""
    topics = Topic.objects.order_by('date_added')
    """创建新贴"""
    if request.method != 'POST':
        form_topic = TopicForm()
        form_poster = PosterForm()
    else:
        form_topic = TopicForm(request.POST)
        form_poster = PosterForm(request.POST)
        if form_topic.is_valid() and form_poster.is_valid():
            topic = form_topic.save(commit=False)
            topic.floor_many = 1
            topic.owner = request.user
            topic.save()
            new_poster = form_poster.save(commit=False)
            new_poster.owner = request.user
            new_poster.topic = topic
            new_poster.floor = 1
            new_poster.save()
            return HttpResponseRedirect(reverse('tiebas:topics'))
    context = {'topics': topics, 'form_topic': form_topic, 'form_poster': form_poster}
    return render(request, 'tiebas/topics.html', context)

def topic(request, topic_id):
    """显示帖子"""
    topic = Topic.objects.get(id=topic_id)
    posters = topic.poster_set.order_by('date_added')

    """回复帖子"""
    if request.method != 'POST':
        form = PosterForm()
    else:
        form = PosterForm(request.POST)
        if form.is_valid():
            obj = poster.objects.filter(topic_id=topic_id).aggregate(max=Max('floor'))
            new_poster = form.save(commit=False)
            new_poster.owner = request.user
            new_poster.topic = topic
            new_poster.floor = obj['max'] + 1
            new_poster.save()
            topic.floor_many += 1
            topic.save()
            return HttpResponseRedirect(reverse('tiebas:topic', args=[topic_id]))
    context = {'topic': topic, 'posters': posters, 'form': form}

    return render(request, 'tiebas/topic.html', context)

def update_comment(request):
    data = {}
    if request.method == 'POST':
            user = request.user
            text = request.POST.get('reply_text', '')
            poster_id = int(request.POST.get('poster_id', ''))
            new_poster = poster.objects.get(id=poster_id)
            reply_comment_id = int(request.POST.get('reply_comment_id'))

            comment = Poster_reply()
            comment.owner = user
            comment.text = text
            comment.poster = new_poster

            if reply_comment_id != 0:

                obj = Poster_reply.objects.get(id=reply_comment_id)
                comment.by_owner = obj.owner
                data['by_owner'] = obj.owner.username
                data['owner_status'] = True
            else:
                data['owner_status'] = False
            comment.save()

    # referer = request.META.get('HTTP_REFERER', reverse('tiebas:index'))
    # return redirect(referer)
            data['status'] = True
            data['username'] = comment.owner.username
            data['comment_time'] = comment.date_added.strftime('%Y-%m-%d %H:%M:%S')
            data['text'] = comment.text
            data['reply_id'] = comment.id
    else:
        data['status'] = False
    return JsonResponse(data)

def poster_del(request, id):
    if request.method == 'POST':
        poster_id = int(id)
        obj = poster.objects.get(id=poster_id)
        topic_obj = obj.topic
        topic_obj.floor_many = topic_obj.floor_many-1
        topic_obj.save()
        obj.delete()
        return JsonResponse({'status': 'True'})

def reply_del(request, id):
    if request.method == 'POST':
        reply_id = int(id)
        Poster_reply.objects.get(id=reply_id).delete()
        return JsonResponse({'status': 'True'})

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('tiebas:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST['password1'])
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('tiebas:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

tiebas/templates/tiebas/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugin/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/font-awesome/css/font-awesome.min.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'tiebas:index' %}">二次元贴吧</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'tiebas:topics' %}">topics</a> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">欢迎， {{ user.username }}<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">管理中心</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'users:logout' %}">退出</a></li>
            </ul>
          </li>
        {% else %}
          <li><a href="{% url 'users:register' %}">注册</a></li>
          <li><a href="{% url 'users:login' %}">登入</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    {% block content %}{% endblock %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap/js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

tiebas/templates/tiebas/index.html
{% extends "tiebas/base.html" %}
{% block title %}用户登录{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<p>欢迎━(*｀∀´*)ノ亻!来的二次元贴吧</p>
{% endblock %}

{% block js %}

{% endblock%}

tiebas/templates/tiebas/topic.html
{% extends "tiebas/base.html" %}
{% block title %}用户登录{% endblock %}

{% block css %}

{% endblock %}

    {% block content %}
    <p>{{topic}}</p>
    <ul>
        {% for poster in posters %}
        <li id="poster_{{ poster.id }}">
            <p>{{poster.owner}} - </p>
            <p>{{poster.text_poster|linebreaks}}</p>
            <p id="reply_father">{{poster.floor}}楼&nbsp;&nbsp;&nbsp;{{poster.date_added|date:'Y-m-d H:i'}}&nbsp;&nbsp;&nbsp;
                <a href="javascript:replyShow({{ poster.id }});">回复</a>
                {% if poster.owner == request.user %}
                <a href="javascript:posterDel({{ poster.id }});">删除</a>
                {% endif %}</p>
            <div id="reply_form_{{ poster.id }}" style="display:none">
                <div id="reply_list_{{ poster.id }}">
                {% for reply in poster.poster_reply_set.all %}
                    <div id="reply_{{ reply.id }}">
                        {% if reply.by_owner == Null %}
                        <span>{{ reply.owner }}</span>
                        {% else %}
                        <span>{{ reply.owner }}:回复 {{ reply.by_owner }}</span>
                        {% endif %}
                        <span> ({{ reply.date_added|date:'Y-m-d H:i'}}):</span>
                        <div>
                            <span>{{ reply.text }}</span>
                            <a href="javascript:reply({{ reply.id }});">回复</a>
                            {% if reply.owner == request.user %}
                            <a href="javascript:replyDel({{ reply.id }});">删除</a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <form action="{% url 'tiebas:update_comment' %}" id="replyForm_{{ poster.id }}" method="post">
                    {% csrf_token %}
                    <textarea id="reply_text_{{ poster.id }}" name="reply_text"></textarea>
                    <input type="hidden" id="poster_id_{{ poster.id }}" name="poster_id" value="{{ poster.id }}">
                    <input type="hidden" id="reply_comment_{{ poster.id }}" class="reply_comment_id" name="reply_comment_id" value="0">
<!--                    <input type="submit" id="replySubmit_{{ poster.id }}" value="发送">-->
                    <button type="button" id="{{ poster.id }}" onclick="replySubmit({{ poster.id }})">发送</button>
                </form>
            </div>
        </li>
        {% empty %}
        <li>没有回复</li>
        {% endfor %}
    </ul>
    <p>发表回复</p>
    <form action="{% url 'tiebas:topic' topic.id%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">发表</button>
    </form>
    <div>
        <nav aria-label="Page navigation">
          <ul class="pagination">
            <li>
              <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
              <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    </div>
    {% endblock %}

{% block js %}
<script>
        $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
        })
    $(function(){

  });
    function replySubmit(id){
        $.ajax({
            url:"{% url 'tiebas:update_comment' %}",
            type:"POST",
            data:$('#replyForm_'+id).serialize(), //所以字段数据 + csrf token
            dataType:"JSON",
            success:function (res) {
                if(res.status){
                    if(res.owner_status){
                        var comment_html = '<div id="reply_' + res.reply_id + '"><span>' + res.username +
                                     ':回复' + res.by_owner + '</span><span> (' +
                                     res.comment_time + '):</span><div><span>' + res.text +
                                     '</span><a >回复</a><a href="javascript:replyDel(' +
                                     res.reply_id + ');"> 删除</a></div></div>';
                    }else{
                        var comment_html = '<div id="reply_' + res.reply_id + '"><span>' + res.username + '</span><span> (' +
                                     res.comment_time + '):</span><div><span>' + res.text +
                                     '</span><a >回复</a><a href="javascript:replyDel(' +
                                     res.reply_id + ');"> 删除</a></div></div>';
                        }
                    $("#reply_list_"+id).append(comment_html);
                }else{
                       console.log('error');
                }
            }
        })
        $('#reply_text_'+id).val('');
    }
    function reply(reply_comment_id){
            // 设置值
            $('.reply_comment_id').val(reply_comment_id);
        }
    function replyShow(id){
            // 设置值
            $('#reply_comment_id').val(id);
            $("#reply_form_"+id).toggle();
            $('.reply_comment_id').val(0);
        }


        function posterDel(id) {
            var flag = confirm("您真的确定要删除吗？")
            if (flag) {
                var pk = id
                var url = '/poster_del/' + pk + '/'
                $.ajax({
                    url: url,
                    type: "POST",
                    success: function (res) {
                        if(res.status){
                        $('#poster_'+id).remove()
                        }
                    }
                })
            }
        }
        function replyDel(id) {
            var flag = confirm("您确定要删除您的回复吗？")
            if (flag) {
                var pk = id
                var url = '/reply_del/' + pk + '/'
                $.ajax({
                    url: url,
                    type: "POST",
                    success: function (res) {
                        if(res.status){
                        $('#reply_'+id).remove()
                        }
                    }
                })
            }
        }

</script>
{% endblock %}

tiebas/templates/tiebas/topics.html
{% extends "tiebas/base.html" %}
{% block title %}用户登录{% endblock %}

{% block css %}

{% endblock %}


    {% block content %}
    <p>猎人吧</p>
    <ul>
        {% for topic in topics %}
        <li>
            {{ topic.floor_many }} -
            <a href="{% url 'tiebas:topic' topic.id %}">{{topic}}</a> ——
            {{ topic.owner }}
        </li>
        {% empty %}
        <li>没有帖子请创建</li>
        {% endfor %}
    </ul>
    <p>发表新贴</p>
    <form action="{% url 'tiebas:topics' %}" method="post">
        {% csrf_token %}
        {{ form_topic.as_p }}
        <br>
        {{ form_poster.as_p }}
        <button name="submit">发表</button>
    </form>
    <div>
        <nav aria-label="Page navigation">
          <ul class="pagination">
            <li>
              <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
              <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    </div>
    {% endblock content %}

{% block js %}

{% endblock%}

users/templates/users/login.html
{% extends "tiebas/base.html" %}
{% block title %}用户登录{% endblock %}

{% block css %}

{% endblock %}

    {% block content %}

    {% if form.errors %}
    <p>密码错误再输入一次</p>
    {% endif %}
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">登入</button>
        <input type="hidden" name="next" value="{% url 'tiebas:index' %}" />
    </form>
    {% endblock content %}
{% block js %}

{% endblock%}

users/templates/users/register.html
{% extends "tiebas/base.html" %}
{% block title %}用户登录{% endblock %}

{% block css %}

{% endblock %}

    {% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">注册</button>
        <input type="hidden" name="next" value="{% url 'tiebas:index' %}" />
    </form>
    {% endblock content %}
{% block js %}

{% endblock%}